ElevatorAdministrationApplication/Models/ViewModels/ElevatorViewModel.cs
namespace ElevatorAdministrationApplication.Models.ViewModels
{
    public class ElevatorViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public DateTime LastInspection { get; set; }
        public DateTime NextInspection { get; set; }
        public string MaximumWeight { get; set; }
        public bool Reboot { get; set; }
        public bool ShutDown { get; set; }
        public bool Door { get; set; }
        public int Floor { get; set; }
        public int MaxFloor { get; set; }
        public int MinFloor { get; set; }
        public string ElevatorType { get; set; }
        public string ElevatorStatus { get; set; }

    }
}

ElevatorAdministrationApplication/Pages/Elevator/ElevatorDetailsPage.cshtml.cs
using ElevatorAdministrationApplication.Models.ViewModels;
using ElevatorAdministrationApplication.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Azure.Devices;
using Newtonsoft.Json;
using System.Data;

namespace ElevatorAdministrationApplication.Pages.Elevator
{
    [Authorize(Roles = "SecondLine Technician, Field Technician")]
    [BindProperties]
    public class ElevatorDetailsPageModel : PageModel
    {
        //byt till din egna iothub connectionstring
        private readonly string IotHub =
            "HostName=CoderPer-IotHub.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=ma+LRFaad+UGhf/jh36X7aYMV2DlhsJ45OLbAnkzkrU=";

        private readonly IElevatorService _elevatorService;

        public List<SelectListItem> AllFloors { get; set; }
        public int CurrentFloor { get; set; }

        public ElevatorDetailsPageModel(IElevatorService elevatorService)
        {
            _elevatorService = elevatorService;
        }

        public int Id { get; set; }
        public ElevatorViewModel elevator;

        public void OnGet(int id)
        {
            Id = id;
            GetElevator(Id);
            AllFloors = SetAllFloors();
        }

        private void GetElevator(int id)
        {
            elevator = new ElevatorViewModel();

            var result = _elevatorService.GetElevator(id);

            elevator.Id = result.Id;
            elevator.Name = result.Name;
            elevator.Address = result.Address;
            elevator.LastInspection = result.LastInspection;
            elevator.NextInspection = result.NextInspection;
            elevator.MaximumWeight = result.MaximumWeight;
            elevator.Reboot = result.Reboot;
            elevator.ShutDown = result.ShutDown;
            elevator.Door = result.Door;
            elevator.Floor = result.Floor;
            elevator.MaxFloor = result.MaxFloor;
            elevator.MinFloor = result.MinFloor;
            elevator.ElevatorType = result.ElevatorType;
            elevator.ElevatorStatus = result.ElevatorStatus;
        }

        public async Task<IActionResult> OnPostInvokeMethodShutDown(int id)
        {
            try
            {

                //byt till din egna iothub connectionstring i IotHub längst upp
                using ServiceClient serviceClient = ServiceClient.CreateFromConnectionString(IotHub);
                var directMethod = new CloudToDeviceMethod("ShutDown");
                directMethod.SetPayloadJson(JsonConvert.SerializeObject(new { id = id }));
                await serviceClient.InvokeDeviceMethodAsync("elevatorDevice", directMethod);

                Id = id;
                GetElevator(Id);
                return RedirectToPage("ElevatorDetailsPage", new { id = Id });
            }
            catch
            {
                Id = id;
                GetElevator(Id);
                return RedirectToPage("ElevatorDetailsPage", new { id = Id });
            }

        }
        public async Task<IActionResult> OnPostInvokeMethodChangeChangeFloor(int id)
        {
            try
            {

                //byt till din egna iothub connectionstring i IotHub längst upp
                using ServiceClient serviceClient = ServiceClient.CreateFromConnectionString(IotHub);
                var directMethod = new CloudToDeviceMethod("ChangeFloor");
                directMethod.SetPayloadJson(JsonConvert.SerializeObject(new { id = id }));
                await serviceClient.InvokeDeviceMethodAsync("elevatorDevice", directMethod);

                Id = id;
                GetElevator(Id);
                return RedirectToPage("ElevatorDetailsPage", new { id = Id });
            }
            catch
            {
                Id = id;
                GetElevator(Id);
                return RedirectToPage("ElevatorDetailsPage", new { id = Id });
            }

        }

        public async Task<IActionResult> OnPostInvokeMethodReset(int id)
        {
            try
            {
                //byt till din egna iothub connectionstring    
                using ServiceClient serviceClient = ServiceClient.CreateFromConnectionString(IotHub);

                var directMethod = new CloudToDeviceMethod("Reset");
                directMethod.SetPayloadJson(JsonConvert.SerializeObject(new { id = id }));
                await serviceClient.InvokeDeviceMethodAsync("elevatorDevice", directMethod);

                Id = id;
                GetElevator(Id);
                return RedirectToPage("ElevatorDetailsPage", new { id = Id });
            }
            catch
            {
                Id = id;
                GetElevator(Id);
                return RedirectToPage("ElevatorDetailsPage", new { id = Id });
            }


        }

        public async Task<IActionResult> OnPostInvokeDirectMethodDoorAction(int id)
        {
            try
            {
                using ServiceClient serviceClient = ServiceClient.CreateFromConnectionString(IotHub);

                var directMethod = new CloudToDeviceMethod("DoorAction");
                directMethod.SetPayloadJson(JsonConvert.SerializeObject(new { id = id }));
                await serviceClient.InvokeDeviceMethodAsync("elevatorDevice", directMethod);

                Id = id;
                GetElevator(Id);
                return RedirectToPage("ElevatorDetailsPage", new { id = Id });
            }
            catch
            {
                Id = id;
                GetElevator(Id);
                return RedirectToPage("ElevatorDetailsPage", new { id = Id });
            }
        }

        public async Task<IActionResult> OnPostDirectMethodChangeFloor(int id, int currentfloor)
        {
            try
            {
                
                using ServiceClient serviceClient = ServiceClient.CreateFromConnectionString(IotHub);

                var directMethod = new CloudToDeviceMethod("ChangeFloor");
                directMethod.SetPayloadJson(JsonConvert.SerializeObject(new { id = id, floor = currentfloor }));
                await serviceClient.InvokeDeviceMethodAsync("elevatorDevice", directMethod);

                Id = id;
                GetElevator(Id);
                return RedirectToPage("ElevatorDetailsPage", new { id = Id, floor = currentfloor });
            }
            catch
            {
                Id = id;
                GetElevator(Id);
                return RedirectToPage("ElevatorDetailsPage", new { id = Id, floor = currentfloor });
            }
        }
        public List<SelectListItem> SetAllFloors()
        {
            var list = new List<SelectListItem>();

            list.Add(new SelectListItem
            {
                Text = elevator.Floor.ToString(),
                Value = elevator.Floor.ToString()
            });

            for (int i = elevator.MinFloor; i <= elevator.MaxFloor; i++)
            {
                list.Add(new SelectListItem
                {
                    Text = i.ToString(),
                    Value = i.ToString()
                });
            }

            return list;
        }
    }
}

		

ElevatorAdministrationApplication/Pages/Elevator/ElevatorsListPage.cshtml.cs
using ElevatorAdministrationApplication.Models;
using ElevatorAdministrationApplication.Models.ViewModels;
using ElevatorAdministrationApplication.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.Data;

namespace ElevatorAdministrationApplication.Pages.Elevator
{
    [Authorize(Roles = "SecondLine Technician, Field Technician")]
    public class ElevatorsPageModel : PageModel
    {
        private readonly IElevatorService _elevatorService;
        public ElevatorsPageModel(IElevatorService elevatorService)
        {
            _elevatorService = elevatorService;
        }
        public List<ElevatorListViewModel> Elevators { get; set; }

        public void OnGetAsync()
        {
            Elevators = _elevatorService.GetElevators().Select(c => new ElevatorListViewModel()
            {
                Id = c.Id,
                Name = c.Name,
                ElevatorStatus = c.ElevatorStatus
            }).ToList();
        }
    }
}

ElevatorAdministrationApplication/Pages/Elevator/ElevatorDetailsPage.cshtml
@page
@model ElevatorAdministrationApplication.Pages.Elevator.ElevatorDetailsPageModel
@{
}

@if(Model.Id != 0){
    <div class="d-flex justify-content-around">
        <div class="flex-row w-auto">
            <h1>@Model.elevator.Name</h1>

            <h2>Commands</h2>
            <div style="width: 350px">
                <form method="post" asp-page-handler="InvokeMethodReset" asp-route-id="@Model.elevator.Id">
                    <div class="d-flex justify-content-between">
                        <p class="m-2">Reset</p>
                        <label class="switch">
                            <input type="checkbox" checked="@Model.elevator.Reboot" onchange="this.form.submit()" />
                            <span class="slider round"></span>
                        </label>
                    </div>
                </form>
                <form method="post" asp-page-handler="InvokeMethodShutDown" asp-route-id="@Model.elevator.Id">
                    <div class="d-flex justify-content-between">
                        @if (Model.elevator.ShutDown)
                        {
                            <p class="m-2">Turn on</p>
                        } else {
                            <p class="m-2">Turn off</p>
                        }
                        <label class="switch">
                            <input type="checkbox" checked="@Model.elevator.ShutDown" onchange="this.form.submit()" />
                            <span class="slider round"></span>
                        </label>
                    </div>
                </form>
                <form method="post" asp-page-handler="InvokeDirectMethodDoorAction" asp-route-id="@Model.elevator.Id">
                    <div class="d-flex justify-content-between">
                        @if(Model.elevator.Door){
                            <p class="m-2">Close doors</p>
                        } else {
                            <p class="m-2">Open doors</p>
                        }
                        <label class="switch">
                            <input type="checkbox" checked="@Model.elevator.Door" onchange="this.form.submit()" />
                            <span class="slider round"></span>
                        </label>
                    </div>
                </form>

                <h2>Floor</h2>
                <form method="post" asp-page-handler="DirectMethodChangeFloor" asp-route-currentfloor="@Model.CurrentFloor" asp-route-id="@Model.elevator.Id">
                    <div class="form-group">
                        <label asp-for="CurrentFloor" class="control-label">Change floor</label>
                        <select asp-for="CurrentFloor" class="form-control form-select" asp-items="@Model.AllFloors">
                        </select>
                        <span asp-validation-for="CurrentFloor" class="field-validation-error"></span>

                    </div>
                    <button class="btn btn-primary" type="submit">Change Floor</button>
                </form>
                <a class="btn btn-primary" asp-route-id="@Model.elevator.Id" asp-page="/Cases/CreateCasePage">New Case</a>
            </div>
        </div>
        <div class="flex-row">
            <h1>Details</h1>

            <h2>Address</h2>
            <p>@Model.elevator.Address</p>

            <h2>Last inspected</h2>
            <p>@Model.elevator.LastInspection.Year-@Model.elevator.LastInspection.Month-@Model.elevator.LastInspection.Day</p>

            <h2>Next inspection</h2>
            <p>@Model.elevator.NextInspection.Year-@Model.elevator.NextInspection.Month-@Model.elevator.NextInspection.Day</p>

            <h2>Maximum weight</h2>
            <p>@Model.elevator.MaximumWeight Kg</p>
        </div>
    </div>
} else {
    <h1>Elevator does not exist</h1>
}

ElevatorAdministrationApplication/Pages/Elevator/ElevatorsListPage.cshtml
@page
@model ElevatorAdministrationApplication.Pages.Elevator.ElevatorsPageModel
@{
}
<div>
    <h1>Elevators</h1>
    <div class="text-center">
        <table class="table table-bordered">
            <tbody>
                @foreach (var elevator in Model.Elevators)
                {
                    <tr>
                        <td>
                            <a asp-page="ElevatorDetailsPage" asp-route-id="@elevator.Id">
                                @elevator.Name
                            </a>
                        </td>
                        @if (elevator.ElevatorStatus == "Active")
                        {
                            <td class="bg-success">
                                @elevator.ElevatorStatus
                            </td>
                        }
                        else
                        {
                            <td class="bg-danger">
                                @elevator.ElevatorStatus
                            </td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>